totalMoney = float(input())

# Fuck this, you need to add 0.0001 to initial value or it breaks sometimes? That doesn't make sense.
[banknotes100, remainder] = divmod(totalMoney + 0.0001, 100)
[banknotes50, remainder] = divmod(remainder, 50)
[banknotes20, remainder] = divmod(remainder, 20)
[banknotes10, remainder] = divmod(remainder, 10)
[banknotes5, remainder] = divmod(remainder, 5)
[banknotes2, remainder] = divmod(remainder, 2)

[coins100, remainder] = divmod(remainder, 1)
[coins50, remainder] = divmod(remainder, 0.5)
[coins25, remainder] = divmod(remainder, 0.25)
[coins10, remainder] = divmod(remainder, 0.1)
[coins5, remainder] = divmod(remainder, 0.05)
[coins1, _remainder] = divmod(remainder, 0.01)

print("NOTAS:")
print(f"{int(banknotes100)} nota(s) de R$ 100.00")
print(f"{int(banknotes50)} nota(s) de R$ 50.00")
print(f"{int(banknotes20)} nota(s) de R$ 20.00")
print(f"{int(banknotes10)} nota(s) de R$ 10.00")
print(f"{int(banknotes5)} nota(s) de R$ 5.00")
print(f"{int(banknotes2)} nota(s) de R$ 2.00")
print("MOEDAS:")
print(f"{int(coins100)} moeda(s) de R$ 1.00")
print(f"{int(coins50)} moeda(s) de R$ 0.50")
print(f"{int(coins25)} moeda(s) de R$ 0.25")
print(f"{int(coins10)} moeda(s) de R$ 0.10")
print(f"{int(coins5)} moeda(s) de R$ 0.05")
print(f"{int(coins1)} moeda(s) de R$ 0.01")
