totalMoney = int(input())

[banknotes100, remainder] = divmod(totalMoney, 100)
[banknotes50, remainder] = divmod(remainder, 50)
[banknotes20, remainder] = divmod(remainder, 20)
[banknotes10, remainder] = divmod(remainder, 10)
[banknotes5, remainder] = divmod(remainder, 5)
[banknotes2, remainder] = divmod(remainder, 2)
[banknotes1, _remainder] = divmod(remainder, 1)

print(f"{totalMoney}")
print(f"{banknotes100} nota(s) de R$ 100,00")
print(f"{banknotes50} nota(s) de R$ 50,00")
print(f"{banknotes20} nota(s) de R$ 20,00")
print(f"{banknotes10} nota(s) de R$ 10,00")
print(f"{banknotes5} nota(s) de R$ 5,00")
print(f"{banknotes2} nota(s) de R$ 2,00")
print(f"{banknotes1} nota(s) de R$ 1,00")
